
function randomWord() {

    var listOfWords = ["javascript", "computer", "syntax", "assignment", "bootcamp", "coding"];
    var randomIndex = listOfWords[Math.floor(Math.random()*listOfWords.Length)];
    var randomgenWord = listOfWords[randomIndex];
    console.log(randomWord)}
    var randomgenWordLength = randomgenWord.length;

    var dashes = document.getElementById("#dashes")
    dashes = [];
    for (var i=0; i < randomWordLength; i++) {
        dashes.push(randomWord[i].replace(/[a-zA-Z/,g, "_"]));
    var displayDashes = dashes.join("");
        

    }
/*function startPlay() {
document.getElementById('startButton').style.display="block"
var startButton = document.getElementById("#startButton")
startButton.addEventlistener("clicked", function(playGame))
console.log("clicked")

   
}*/



var alphabetArray = ["abcdefghijklmnopqrstuvwxys"]; //array of alphabets to map
var counter = 0;
var score = {
    wins: 0,
    losses: 0;
}


//

//Timer element
var timerEl = document.getElementById('#timer');
/*var mainEl = document.getElementById('main');

//var message = 
*/

var time = document.querySelector(".timer")
function countdown() {
    var timeLeft = 60;
    var timeInterval = setInterval(function () {
    if (timeleft === 0) {
        timerEl.textContent = timeLeft;
        clearInterval(timeInterval);
        //.textContent = "You lose"
    } else if (timeLeft > 1) {
        timerEl.textContent = timeLeft + ' seconds remaining';
        timeLeft--;
    } 
},60000); }
countdown();






//generate random word from list of words in the array


//generate underscores to match the word randomly generated by Math

        
    

/*
var wordArray = selectedWord.split(",");
console.log(listOfWords)



function keydownAction(event) {
    console.log(event);
    var keyPress = event.key;
    var wordKeyboard = String.fromCharCode(event.key);
    

    document.querySelector("#key").textContent = keyPress;
    document.addEventListener("keydown", keydownAction);



}
}

*/









